

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.**.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level.com.rent.mapper: debug
  file: ./logs/myapp.log

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false