web:
  upload-path: /data/upload
server:
  port: 80
spring:
  datasource:

    url: jdbc:mysql://3.91.54.36:3306/rent_system?characterEncoding=utf8
    username: root
    password: rent_123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/static/upload","classpath:/public/","classpath:/templates/","file:${web.upload-path}","file:/static/"]
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.**.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level.com.rent.mapper: debug


